CREATE TABLE IF NOT EXISTS TEMPORARY_FILE
(
    ID                   UUID PRIMARY KEY,
    FILE_NAME            VARCHAR(255) UNIQUE NOT NULL,
    EXPIRATION_DATE      TIMESTAMP           NOT NULL,
    CREATED_AT           TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY           UUID                NOT NULL
    );

